### ISSUE TITLE
Delete old blog posts from _posts, change home page information

### ISSUE THREAD

**Issue by ashlynnhelm** [ashlynnhelm/team5_project2.2#2]
Need to hide/delete the sample posts from the _posts folder, and then change the information on the home page such as title, website description.

**Comment by alancavazos** [comment]
Added the "About Alan" blog page, and then changed the _config file to update the landing page to our liking

**Comment by hunterthor** [comment]
Added the "About Hunter" page to the website, and then deleted the sample posts from the _posts folder to clear up some space.
